### PR TITLE
Add explanation about the WebSocket import

### PR DESCRIPTION
**Pull request by eoger**

### CODE REVIEW

**Comment by vladikoff** [comment]
@eoger isn't it supposed to go here: https://github.com/mozilla/fxa-pairing-channel/blob/35356f339099894136e452884287276cc6fda716/src/jsm_header.js.inc ???

**Comment by vladikoff** [comment]
Otherwise it would be overwritten the next time we build?

**Comment by eoger** [comment]
Oh yeah :facepalm:

**Comment by vladikoff** [comment]
> Oh yeah :facepalm:

That's ok :)

**Pull request merged**
